### ISSUE TITLE
VPN/container env script and process enhance

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#266]
In GitLab by @mvesin on Apr 29, 2022, 14:07

As a user (more precisely: IT team(s) deploying an instance of Fed-BioMed for the real clinical/researcher/data-scientist end-user) i want better script/packaging so as to deploy more easily a Fed-BioMed instance using VPN/container env.

* This comes as a followup of #138 (`fedbiomed_vpn` script).
* Target scenario to simplify is the one from `fedbiomed/fedbiomed.gitlabpages.inria.fr` VPN/container deployment tutorial `docs/user-guide/deployment/deployment-vpn.md`.

WIP tasks list for process:
* ~~[ ] update `docker-compose` to v2.x (newer version of docker come with a 2.x `docker compose` ; standalone compose install is being abandonned https://docs.docker.com/compose/install/ )~~ done in #448
* [x] use a dedicated (bridge) network instead of the default `bridge`
* [ ] consider replacing wireguard implementation boringtun by a more widely adopted/distributed (through package manager) implementation (`wireguard`, `wireguard-go`)

WIP tasks list for env script:
* [ ] add support for GPU
* [ ] add `fedbiomed_vpn configure node NODETAG` (currently you can't specify NODETAG, "node1" is hardcoded, so it is not usable for multiple nodes deployment)
* [ ] (optional, requires modifying GUI) modify GUI so that it can be launched when no `${FEDBIOMED_DIR}/etc/config_node.ini` exists (eg: periodic retries to see if `config_node.ini` was created)
* [ ] modify `fedbiomed_vpn start` (at least `fedbiomed_vpn start node`: test if `vpnserver` container is running. If not, write message "vpnserver not on this machine, register node public key from file xxx on vpnserver"
* [ ] (also requires modifying `configure_peer.py genconf`, entrypoint scripts, etc.) add `MQTT_BROKER(_PORT)` and `UPLOADS_URL` to `config.env` file
  * goal: auto-transmit infos from vpnserver to containers
* ~~[ ] modify `fedbiomed_vpn {node,researcher}` to use `MQTT_BROKER(_PORT)` and `UPLOADS_URL` from `config.env` (don't try to guess them anymore)~~
* [ ] add `fedbiomed_vpn run {node,researcher}` to run arbitry command in the container as the user (`$(id -u)`) eg
  * `fedbiomed_vpn run node bash` for interactive session
  * `fedbiomed_vpn run node uname -a`
* [x] add support for ~~handling node (`fedbiomed_run node start`) as a `systemd` service~~ *starting node automatically (maybe as a service)* in the node container => implemented in #1296 (not a systemd service)
* [ ] add support for handling node (`fedbiomed_run node start`) as a `systemd` service => issue #1300
* ~~[ ] add `fedbiomed_vpn node-service {start,stop,status}` for restarting node-as-a-systemd-service easily (connect to container as root and launch service as user)~~ not implemented as a service (see #1296)
* [ ] extend `fedbiomed_vpn configure` (or add a `fedbiomed_vpn certificate-vpn-setup) for fully automating VPN configuration in the case researcher + 2 nodes are running in the same clone
* ~~[ ] extend `fedbiomed_vpn certificate-vpn-setup` wizard for configuring secagg certificates in the case researcher + 2 nodes are running in the same clone~~
* [ ] optionally implement #521 for nicer handling of multiple nodes on one machine
* ~~[ ] support versions in docker images~~ => done in #1303  
* ~~[] improve containers network configuration isolation~~ => done in #1306 
* [ ] implement #1308 for running multiple instances simultaneously
* [ ] implement #1313 for improving container launch speed under another identity than the one used for build
* [ ] document and support scenario with vpnserver and researcher running on different machines
* [ ] support non-hardcoded component IP
* [ ] add trafic filter in VPN (by IP address ?)
* [ ] support running a container without being in development mode (no git clone)
