### ISSUE TITLE
Redefine the process in order to use: product goals, milestones, issues and labels

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#415]
In GitLab by @mvesin on Nov 21, 2022, 13:07

As an agile team we want to evolve the [current process](https://fedbiomed.gitlabpages.inria.fr/latest/developer/usage_and_tools/#organization) for managing milestones/issues/labels in Fed-BioMed

- [x] write draft proposal
- [x] submit proposal to the team for feedback (meeting ? interactive ?)
- [x] write final retained process to gitlabpages
- [x] update existing milestones/issues/labels to match new process (with scrum master ?)
  * review all issues
  * remove obsolete labels (postponed, improvement, feature, intersprint) from issues
  * add labels describing status in new process
  * delete obsolete labels

Points decided:
- remove some ("misc") tags:
  * postponed
  * improvement
  * feature
  * intersprint
- don't add new tags for "priority1/2/3/4"
