### ISSUE TITLE
work on github migration

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#512]
In GitLab by @ErwanDemairy on Apr 18, 2023, 15:48

# Scope
- scope: includes library, probably includes documentation githubpages
- scope: configure fedbiomed.org (assess DNS and/or HTTP redir 301/302), based on #526
- not in scope: not CI, not user support slack, not list

# Subtasks
- [x] assessment + decide target and plan (including: merge library/gitlabpages before migrating ? redirection from previous URL for backward compatibility ?)
- [x] optional: do the migration
- [x] WIP tasks
  - [x] create management account(s)
  - [x] get feedback from experienced people
  - [x] PoC on github
  - [x] define which features of github to use? (deployment target)
  - [x] define Migration plan + backward compatibility plan (eg: keep gitlab site for archive, update docs/processes)
