### ISSUE TITLE
Feature/254 sp15 item12 create nifti dataloader for loading medical images - [merged]

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#649]
In GitLab by @sssilvar on May 18, 2022, 14:38

_Merges feature/254-sp15-item12-create-nifti-dataloader-for-loading-medical-images -> develop_

Closes #254 

## Changelog
* Unit testing added (including synthetic data generation).
* Lenght property of the dataset adjusts depending on the available information.
* Compatible with Dataloaders. Returns a `dict` of `dict` being the first the data source `data, target, demographics` and the other the modalities within each e.g. `T1, T2, label, AGE, CENTER_NAME`.
* Multi-format support for demographics file (`tabular_file`): CSV, TSV, Excel.

## Todo for #290 
* [x] Add necessary attributes, properties, and methods for GUI.
* [x] Adjust the model gathered by @sayed so data can be extracted in a compatible manner at each `training_step`. 
* [x] Finishing refactoring by @mvesin 

## Extensions:  

- Create class called `BIDSBase` where BIDS folder structure and reference verification operations are provided
- `BIDSDataset` inherits `BIDSBase`
- Create BIDSController that inherits `BIDSBase`. This class is used for dataset deployment actions.
